version: "3.5"
services:
  #PHP Service
  pedigree-php-base:
    build:
      context: .
      dockerfile:  ./docker/app/php-base/7.4/Dockerfile
  pedigree-php:
    build:
      context: .
      dockerfile: ./docker/app/php/production/Dockerfile
    container_name: pedigree-php
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html/public
    networks:
      - app-network
    depends_on: 
      - webserver
      - mysql
  #Nginx Service
  webserver:
    build:
      context: .
      dockerfile: ./docker/app/nginx/Dockerfile
    container_name: pedigree-nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network
  #MySQL Service
  mysql:
    image: mysql:8.0.22
    container_name: pedigree_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - pedigree-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pedigree
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  redis:
    container_name: pedigree-app-cache
    image: redis:6.0-alpine
    volumes:
      - pedigree-cache:/data
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  pedigree-db:
    driver: local
  pedigree-cache:
    driver: local
