name: Build & Push Production PHP-Base 7.4 Image
on:
  push:
    branches:
      - master
    paths:
      - 'docker/app/php-base/7.4/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Build Docker image and Push to ECR
      uses: kciter/aws-ecr-action@master
      env:
        repo: pedigree/php-base
      with:
        access_key_id: ${{ secrets.OSO_PROD_AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.OSO_PROD_AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.OSO_PROD_AWS_ACCOUNT_ID }}
        dockerfile: ./docker/app/php-base/7.4/Dockerfile
        path: ./
        repo: ${{ env.repo }}
        region: eu-west-2
        tags: 7.4
        create_repo: false
